plank:
  default_decoration_config:
    utility_images: # using the tag we identified above
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190911-0708557a1"
      initupload: "gcr.io/k8s-prow/initupload:v20190911-0708557a1"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190911-0708557a1"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190911-0708557a1"
    gcs_configuration:
      bucket: prow-artifacts-wrefvem # the bucket we just made
      path_strategy: explicit
    gcs_credentials_secret: gcs-credentials # the secret we just made

prowjob_namespace: prow
pod_namespace: test-pods

postsubmits:
  foghornci/foghorn:
  - name: test-postsubmit
    decorate: true
    spec:
      containers:
      - image: alpine
        command: 
        - "go"
        args:
        - "test -v ./..."
presubmits:
  foghornci/foghorn:
  - name: test-presubmit
    decorate: true
    always_run: true
    skip_report: false
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
    spec:
      containers:
      - image: alpine
        command: 
        - "go"
        args:
        - "test -v ./..."
